FancyProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('product/', include('product.urls')),
    path('others/', include('others.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import Bloghome, Blogdetails, AddPost,UpdatePost,DeletePost

app_name = 'blog'

urlpatterns = [
    path('', Bloghome.as_view(), name='bloghome'),
    path('blogdetails/<int:pk>', Blogdetails.as_view(), name='blogdetails'),
    # path('blogdetails/<slug:slug>', Blogdetails.as_view(), name='blogdetails'),
    # path('add_post/', AddPost.as_view(), name='add_post'),
    # path('edit_post/<slug:slug>', UpdatePost.as_view(), name='edit_post'),
    # path('delete_post/<slug:slug>/remove', DeletePost.as_view(), name='delete_post'),
    # # path('like/<int:pk>', LikeView, name='like_post'),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('gallery', views.gallery, name='gallery'),
    path('search/', views.search, name='search'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('term_conditions/', views.term_conditions, name='term_conditions'),

]

others/urls.py
from django.urls import path
from . import views

app_name = 'others'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('career/', views.career, name='career'),
    path('<slug:dept_slug>', views.career,name='dept_slug'),
    path('career/details', views.job_details, name='job_details'),
    path('apply/', views.job_apply, name='job_apply'),

]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product, name='product'),
    path('<slug>', views.product, name='cat_slug'),
    path('product_details/<slug>', views.product_details, name='product_details'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.TextField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null= True)
    blog_image = models.ImageField(upload_to='blognew/image', default='')
    time = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    slug = models.SlugField(null=True)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + '  |  ' + str(self.author)

    def snippet(self):
        return self.body[:30]

    def get_absolute_url(self):
        return reverse('blog:blogdetails', kwargs={'slug': self.slug})

home/models.py
from django.db import models
from product.models import Category
from django_resized import ResizedImageField

# Create your models here.

class upcoming_Product(models.Model):
    product_title = models.CharField(max_length=50)
    product_category = models.ForeignKey(Category, on_delete=models.PROTECT)
    image = ResizedImageField(size=[500, 320], crop=['middle', 'center'], quality=100, upload_to='upcoming_Product/image', default='')

    def __str__(self):
        return self.product_title

    def get_absolute_url(self):
        return reversed('home:home')


class Best_Values(models.Model):
    img = models.ImageField(upload_to='best_values/image', help_text='small size=370x200 & big size=1170x370 recommended*')
    is_big = models.BooleanField(default = False)


class Gallery(models.Model):
    gallery_title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='pv/image', null=True)
    video_url = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.gallery_title

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','body','blog_image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'elder', 'type':'hidden'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'blog_image': forms.FileInput(attrs={'class': 'form-control'}),
        }



class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body','blog_image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'blog_image': forms.FileInput(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView , CreateView, UpdateView, DeleteView
from .models import Post
from .forms import PostForm,EditForm

# def LikeView(request,pk):
#     post =get_object_or_404(Post, id=request.POST.get('post_id'))
#     liked = False
#     if post.likes.filter(id=request.user.id).exists():
#         post.likes.remove(request.user)
#         liked = False
#     else:
#         post.likes.add(request.user)
#         liked = True
#     return HttpResponseRedirect(reverse('blog:blogdetails', args=[str(pk)]))


class Bloghome(ListView):
    model = Post
    template_name = 'blog/blog.html'
    ordering = ['id']
    paginate_by = 2


class Blogdetails(DetailView):
    model = Post
    template_name = 'blog/blogdetails.html'

    # def get_context_data(self, **kwargs):
    #     context = super(Blogdetails, self).get_context_data(**kwargs)
    #     stuff = get_object_or_404(Post, id=self.kwargs['pk'])
    #     total_likes = stuff.total_likes()
    #
    #     liked = False
    #     if stuff.likes.filter(id=self.request.user.id).exists():
    #         liked = True
    #     context ["total_likes"] = total_likes
    #     context["liked"] = liked
    #     return context


class AddPost(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/add_post.html'


class UpdatePost(UpdateView):
    model = Post
    form_class = EditForm
    template_name = "blog/update_post.html"


class DeletePost(DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = reverse_lazy('blog:bloghome')

home/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import upcoming_Product, Best_Values,Gallery
from product.models import Category, Products
from blog.models import Post

# Create your views here.

def home(request):
    upcoming_product = upcoming_Product.objects.all()
    category = Category.objects.all()
    bestproduct= Best_Values.objects.order_by('is_big')
    blog = Post.objects.all()
    gallery = Gallery.objects.all()
    return render(request, 'home/index.html', {'coming_pr': upcoming_product,
                                              'category': category,
                                              'bestvalue': bestproduct,
                                              'blog': blog,
                                              'gallery': gallery})



def gallery(request):
    gallery = Gallery.objects.all()
    paginator = Paginator(gallery, 4)
    page = request.GET.get('page')
    gallery = paginator.get_page(page)
    return render(request, 'home/video_&_image.html', {'gallery':gallery})


def search(request):
    query = request.GET['search']
    productName = Products.objects.filter(product_name__icontains=query)
    productdetails = Products.objects.filter(Product_details__icontains=query)
    allPost = productName.union(productdetails)
    total = {'allPost': allPost, 'query': query}
    return render(request,'home/search.html', total)


def privacy_policy(request):
    return render(request, 'home/privacy_policy.html')


def term_conditions(request):
    return render(request, 'home/term_conditions.html')

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, shrink-to-fit=9">
		<meta name="description" content="Gambolthemes">
		<meta name="author" content="Gambolthemes">
		<title>{% block title %} Fancy Group Limited{% endblock %}</title>

		<!-- Favicon Icon -->
		<link rel="icon" type="image/png" href="{% static 'images/fav.png' %}">

		<!-- Stylesheets -->
		<link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
		<link href='{% static 'vendor/unicons-2.0.1/css/unicons.css' %}' rel='stylesheet'>
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
		<link href="{% static 'css/night-mode.css' %}" rel="stylesheet">

		<!-- Vendor Stylesheets -->
		<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
		<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'vendor/semantic/semantic.min.css' %}">

    {% block header %}
    {% endblock header %}

	</head>

<body>

    {% include 'home/header.html' %}
	<!-- Body Start -->
		{% block body %}
        {% endblock body %}
    <!-- Body End -->

	<!-- Footer Start -->
    {% include 'home/footer.html' %}
	<!-- Footer End -->

	<!-- Javascripts -->
	<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/OwlCarousel/owl.carousel.js' %}"></script>
	<script src="{% static 'vendor/semantic/semantic.min.js' %}"></script>
	<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="{% static 'js/offset_overlay.js' %}"></script>
	<script src="{% static 'js/night-mode.js' %}"></script>

</body>
</html>

home/templates/home/best_value.html
{% load static %}
<div class="section145">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main-title-tt">
                    <div class="main-title-left">
                        <h2>Best Values </h2>
                    </div>
                </div>
            </div>
            {% for item in bestvalue %}
                {% if item.is_big %}
                    <div class="col-md-12">
                        <div class="code-offer-item">
                            <img src="/media/{{ item.img }}" alt="">
                        </div>
                    </div>
                {% else %}
                    <div class="col-lg-4 col-md-6">
                        <div class="best-offer-item">
                            <img src="/media/{{ item.img }}" alt="">
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

home/templates/home/blog.html
{% load static %}
<div class="section145">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main-title-tt">
                    <div class="main-title-left">
                        <h2>Blog</h2>
                    </div>
                    <a href="{% url 'blog:bloghome' %}" class="see-more-btn">See All</a>
                </div>
            </div>
            <div class="col-md-12">
                <div class="owl-carousel featured-slider owl-theme">
                    {% for item in blog %}
                        <div class="item">
                            <div class="product-item">
                                <a href="{% url 'blog:blogdetails' item.pk %}" class="product-img">
                                    <img src="/media/{{item.blog_image}}" alt="">
                                </a>
                                <div class="product-text-dt">
                                    <h4>{{item.title}}</h4>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

home/templates/home/category.html
{% load static %}
<div class="section145">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main-title-tt">
                    <div class="main-title-left">
                        <h2>Categories</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="owl-carousel cate-slider owl-theme">
                    {% for item in category %}
                        <div class="item">
                            <a href="{{ item.get_absolute_url }}" class="category-item">
                                <div class="cate-img">
                                    <img src="/media/{{item.image}}" alt="">
                                </div>
                                <h4> {{item.category_name}} </h4>
                            </a>
                        </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

home/templates/home/footer.html
{% load static %}

<footer class="footer">
    <div class="footer-first-row">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <ul class="call-email-alt">
                        <li><a href="#" class="callemail"><i class="uil uil-dialpad-alt"></i>0258150228</a></li>
                        <li><a href="#" class="callemail"><i class="uil uil-envelope-alt"></i>info@fancygroupbd.com</a></li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="social-links-footer">
                        <ul>
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-second-row">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="second-row-item">
                        <h4>Categories</h4>
                        <ul>
                            <li><a href="#">Fruits and Vegetables</a></li>
                            <li><a href="#">Grocery & Staples</a></li>
                            <li><a href="#">Dairy & Eggs</a></li>
                            <li><a href="#">Beverages</a></li>
                            <li><a href="#">Snacks</a></li>
                            <li><a href="#">Home Care</a></li>
                            <li><a href="#">Noodles & Sauces</a></li>
                            <li><a href="#">Personal Care</a></li>
                            <li><a href="#">Pet Care</a></li>
                            <li><a href="#">Meat & Seafood</a></li>
                            <li><a href="#">Electronics</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="second-row-item">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><a href="#">About US</a></li>
                            <li><a href="#">Featured Products</a></li>
                            <li><a href="#">Offers</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Faq</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="second-row-item">
                        <h4>Products</h4>
                        <ul>
                            <li><a href="#">Biscuits</a></li>
                            <li><a href="#">Candy</a></li>
                            <li><a href="#">Ghee</a></li>
                            <li><a href="#">Semai</a></li>
                            <li><a href="#">Snacks</a></li>
                            <li><a href="#">Tea</a></li>
                            <li><a href="#">Spice</a></li>
                            <li><a href="#">Noodles</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="second-row-item-app">
                        <h4>Download App</h4>
                        <ul>
                            <li><a href="#"><img class="download-btn" src="{% static 'images/download-1.svg' %}" alt=""></a></li>
                            <li><a href="#"><img class="download-btn" src="{% static 'images/download-2.svg' %}" alt=""></a></li>
                        </ul>
                    </div>
                    <div class="second-row-item-payment">
                        <h4>Payment Method</h4>
                        <div class="footer-payments">
                            <ul id="paypal-gateway" class="financial-institutes">
                                <li class="financial-institutes__logo">
                                  <img alt="Visa" title="Visa" src="{% static 'images/footer-icons/pyicon-6.svg' %}">
                                </li>
                                <li class="financial-institutes__logo">
                                  <img alt="Visa" title="Visa" src="{% static 'images/footer-icons/pyicon-1.svg' %}">
                                </li>
                                <li class="financial-institutes__logo">
                                  <img alt="MasterCard" title="MasterCard" src="{% static 'images/footer-icons/pyicon-2.svg' %}">
                                </li>
                                <li class="financial-institutes__logo">
                                  <img alt="American Express" title="American Express" src="{% static 'images/footer-icons/pyicon-3.svg' %}">
                                </li>
                                <li class="financial-institutes__logo">
                                  <img alt="Discover" title="Discover" src="{% static 'images/footer-icons/pyicon-4.svg' %}">
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="second-row-item-payment">
                        <h4>Newsletter</h4>
                        <div class="newsletter-input">
                            <input id="email" name="email" type="text" placeholder="Email Address" class="form-control input-md" required="">
                            <button class="newsletter-btn hover-btn" type="submit"><i class="uil uil-telegram-alt"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-last-row">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="footer-bottom-links">
                        <ul>
                            <li><a href="{% url 'others:about' %}">About</a></li>
                            <li><a href="{% url 'others:contact' %}">Contact</a></li>
                            <li><a href="{% url 'home:privacy_policy' %}">Privacy Policy</a></li>
                            <li><a href="{% url 'home:term_conditions' %}">Term & Conditions</a></li>
                        </ul>
                    </div>
                    <div class="copyright-text">
                        <i class="uil uil-copyright"></i>Copyright 2020 <b>Fancy Group</b> . All rights reserved
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

home/templates/home/gallery.html
{% load static %}
<div class="section145">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="main-title-tt">
                    <div class="main-title-left">
                        <h2>Gellary</h2>
                    </div>
                    <a href="{% url 'home:gallery' %}" class="see-more-btn">See All</a>
                </div>
            </div>
            <div class="col-md-12">
                <div class="owl-carousel featured-slider owl-theme">
                     {% for item in gallery %}
                        <div class="item">
                            <div class="product-item">
                                <a href="{% url 'home:gallery' %}" class="product-img">
                                    <img  src="/media/{{item.image}}" class="img-fluid" alt="">
                                </a>
                                <div class="product-text-dt">
                                    <h4>{{item.gallery_title}}</h4>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

home/templates/home/header.html
	{% load static %}
	<!-- Header Start -->
	<header class="header clearfix">
		<div class="top-header-group">
			<div class="top-header">
				<div class="res_main_logo">
					<a href="index.html"><img src="{% static 'images/dark-logo-1.svg' %}" alt=""></a>
				</div>
				<div class="main_logo" id="logo">
					<a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
					<a href="/"><img class="logo-inverse" src="{% static 'images/logo.png' %}" alt=""></a>
				</div>
				<div class="search120">
					<div class="ui search">
					  <form method="get" action="{% url 'home:search' %}" class="ui left icon input swdh10">
						<input name="search" id="search" class="prompt srch10" type="text" placeholder="Search for products..">
						<i class='uil uil-search-alt icon icon1'></i>
					  </form>
					</div>
				</div>
				<div class="header_right">
					<ul>
						<li>
							<a href="#" class="offer-link"><i class="uil uil-phone-alt"></i>0258150228</a>
						</li>
{#						<li>#}
{#							<a href="#" class="offer-link"><i class="uil uil-gift"></i>Offers</a>#}
{#						</li>#}
{#						<li>#}
{#							<a href="#" class="offer-link"><i class="uil uil-question-circle"></i>Help</a>#}
{#						</li>#}
						<li class="ui dropdown">
							<div class="night_mode_switch__btn">
                                <a href="#" id="night-mode" class="btn-night-mode">
                                    <i class="uil uil-moon"></i> Night mode
                                    <span class="btn-night-mode-switch">
                                        <span class="uk-switch-button"></span>
                                    </span>
                                </a>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="sub-header-group">
			<div class="sub-header">

				<nav class="navbar navbar-expand-lg navbar-light py-3">
					<div class="container-fluid">
						<button class="navbar-toggler menu_toggle_btn" type="button" data-target="#navbarSupportedContent"><i class="uil uil-bars"></i></button>
						<div class="collapse navbar-collapse d-flex flex-column flex-lg-row flex-xl-row justify-content-lg-end bg-dark1 p-3 p-lg-0 mt1-5 mt-lg-0 mobileMenu" id="navbarSupportedContent">
							<ul class="navbar-nav main_nav align-self-stretch">
								<li class="nav-item"><a href="/" class="nav-link active" title="Home">Home</a></li>
								<li class="nav-item"><a href="{% url 'product:product' %}" class="nav-link new_item" title="New Products">Products</a></li>
								<li class="nav-item"><a href="{% url 'others:career' %}" class="nav-link" title="Career">Career</a></li>
								<li class="nav-item"><a href="{% url 'blog:bloghome' %}" class="nav-link" title="Blog">Blog</a></li>
								<li class="nav-item"><a href="{% url 'home:gallery' %}" class="nav-link" title="Blog">Gallery</a></li>
								<li class="nav-item"><a href="{% url 'others:about' %}" class="nav-link" title="Contact">About Us</a></li>
								<li class="nav-item"><a href="{% url 'others:contact' %}" class="nav-link" title="Contact">Contact Us</a></li>
							</ul>
						</div>
					</div>
				</nav>
				<div class="catey__icon">
					<a href="#" class="cate__btn" data-toggle="modal" data-target="#category_model" title="Categories"><i class="uil uil-apps"></i></a>
				</div>

				<div class="search__icon order-1">
					<a href="#" class="search__btn hover-btn" data-toggle="modal" data-target="#search_model" title="Search"><i class="uil uil-search"></i></a>
				</div>
			</div>
		</div>
	</header>
	<!-- Header End -->

home/templates/home/home.html
{% extends 'home/base.html' %}
{% block body %}

{#  <!-- Upcoming product -->#}
{##}
{#<div id="demo" class="carousel slide" data-ride="carousel">#}
{#<ul class="carousel-indicators">#}
{#  <li data-target="#demo" data-slide-to="0" class="active"></li>#}
{#  {% for i in range %}#}
{#  <li data-target="#demo" data-slide-to="{{i}}" ></li>#}
{#  {% endfor %}#}
{#</ul>#}
{##}
{#<div class="carousel-inner no padding">#}
{#<div class="carousel-item active">#}
{# {% for i in coming_pr %}#}
{#<div class="col-xs-3 col-sm-3 col-md-3">#}
{#   <div class="card my-4" style="width: 23rem; height: 15rem ; background-image: url('/media/{{i.image}}');">#}
{#       <div style="background-color: white; width: 13rem; height: auto " class="my-4" >#}
{#       <h5 class="card-title mx-3">{{i.product_title }}</h5>#}
{#        <p class="card-text mx-3">{{i.Product_category }}</p>#}
{#       </div>#}
{##}
{#</div>#}
{#</div>#}
{##}
{#  {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}#}
{#</div>#}
{#<div class="carousel-item ">#}
{#{% endif %}#}
{#{% endfor %}#}
{#</div>#}
{#</div>#}
{#</div>#}


    <!-- product_category -->


<div id="demo1" class="carousel slide my-4" data-ride="carousel">
<ul class="carousel-indicators">
  <li data-target="#demo1" data-slide-to="0" class="active"></li>
  {% for i in cat_range %}
  <li data-target="#demo1" data-slide-to="{{i}}" ></li>
  {% endfor %}
</ul>

<div class="container carousel-inner ">
<h2 class="my-5">Category</h2>
<div class="carousel-item active">
 {% for i in cat %}
<div class="col-xs-3 col-sm-3 col-md-3 ">

<div class="card" style="width: 18rem;">
    <img src='/media/{{i.image}}' class="card-img-top" alt="cat">
       <div class="card-body">
            <h5 class="card-text">{{i.category_name }}</h5>
       </div>
</div>

</div>
{% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
</div>
<div class="carousel-item ">
{% endif %}
{% endfor %}
</div>

         <!-- Best_product-->

<h2 class="my-5">Best Values</h2>

{% for i in bestpro %}

<div class="col-lg-4 col-md-6" style=" display: inline-block;
    margin-left: -4px;">

		<a href="#" class="best-offer-item">
            <img src="/media/{{i.img}}" alt="">
		</a>
</div>

{% endfor %}

   <!-- Blog-->

        <div class="section145">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="main-title-tt">
							<div class="main-title-left">
								<span>Danish</span>
								<h2 class="my-4">Blog</h2>
							</div>
						</div>
					</div>


					<div class="col-md-12">
						<div class="owl-carousel featured-slider owl-theme">
							<div class="item">
                                {% for i in blog %}

								<div class="product-item" style=" display: inline-block; margin-left: -4px;">
									<a href="#" class="product-img mr-4">
										<img src="/media/{{i.blog_image}}" alt="" style="width: 10rem; height: 10rem">
									</a>
									<div class="product-text-dt">
										<h4>{{i.blog_title}}</h4>
									</div>
								</div>
                                    {% endfor %}
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

 <!-- Gallery-->

<!-- New Products Start -->
		<div class="section145">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="main-title-tt">
							<div class="main-title-left">
								<span>Danish</span>
								<h2 class="my-4">Photo & Video Gallary</h2>
							</div>
							<a href="#" class="see-more-btn">See All</a>
						</div>
					</div>
					<div class="col-md-12">
						<div class="owl-carousel featured-slider owl-theme">
							<div class="item" >
                                {% for i in gallery %}

								<div class="product-item"  style=" display: inline-block; margin-left: -4px;">
									<a href="#" class="product-img mr-4">
										<img src="/media/{{i.pv_image}}" alt="" style="width: 10rem; height: 10rem">
									</a>
									<div class="product-text-dt">
										<h4>{{i.pv_title}}</h4>
									</div>
								</div>
					               {% endfor %}
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>



</div>
</div>


{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}

{% block body %}
<div class="wrapper">

    <!-- Offers Start -->
{% include 'home/slider.html' %}
<!-- Offers End -->
<!-- Categories Start -->
{% include 'home/category.html' %}

<!-- Featured Products End -->
<!-- Best Values Offers Start -->
 {% include 'home/best_value.html' %}
<!-- Best Values Offers End -->
<!-- Vegetables and Fruits Start -->
{% include 'home/blog.html' %}
<!-- Vegetables and Fruits Products End -->
<!-- New Products Start -->
{% include 'home/gallery.html' %}
<!-- New Products End -->
</div>
{% endblock body %}

home/templates/home/privacy_policy.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <div class="wrapper">
        <h1>privacy_policy page</h1>
    </div>
{% endblock %}

home/templates/home/term_conditions.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <div class="wrapper">
        <h1>term_conditions page</h1>
    </div>
{% endblock %}