FancyProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('product/', include('product.urls')),
    path('others/', include('others.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import Bloghome, Blogdetails, AddPost,UpdatePost,DeletePost

app_name = 'blog'

urlpatterns = [
    path('', Bloghome.as_view(), name='bloghome'),
    path('blogdetails/<int:pk>', Blogdetails.as_view(), name='blogdetails'),
    # path('blogdetails/<slug:slug>', Blogdetails.as_view(), name='blogdetails'),
    # path('add_post/', AddPost.as_view(), name='add_post'),
    # path('edit_post/<slug:slug>', UpdatePost.as_view(), name='edit_post'),
    # path('delete_post/<slug:slug>/remove', DeletePost.as_view(), name='delete_post'),
    # # path('like/<int:pk>', LikeView, name='like_post'),
]

others/urls.py
from django.urls import path
from . import views

app_name = 'others'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('career/', views.career, name='career'),
    path('<slug:dept_slug>', views.career,name='dept_slug'),
    path('career/details', views.job_details, name='job_details'),
    path('apply/', views.job_apply, name='job_apply'),

]

others/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField

# Create your models here.


class Contact(models.Model):
    full_name = models.CharField(max_length=100, default='')
    emailaddress = models.CharField(max_length=100)
    subject = models.CharField(max_length=500)
    message = models.TextField(default='')

    def __str__(self):
        return self.full_name


class Team(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    image = ResizedImageField(size=[500, 500], crop=['middle', 'center'], quality=100, upload_to='team/image', default='')
    details = RichTextField(blank=True, null=True)
    facebookId = models.CharField(max_length=225, default='', blank=True)
    linkedinId = models.CharField(max_length=225, default='', blank=True)

    def __str__(self):
        return self.name


class Departments(models.Model):
    department_name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.department_name

    def get_absolute_url(self):
        return reverse('others:dept_slug', args=[self.slug, ])


class Circular(models.Model):
    JOB_TYPE = (
        ('FULL-TIME', 'FULL-TIME'),
        ('CONTRACTUAL', 'CONTRACTUAL'),
        ('PART-TIME', 'PART-TIME'),
        ('REMOTE', 'REMOTE'),
    )
    job_title = models.CharField(max_length=255)
    job_details = RichTextField(blank=True, null=True)
    job_type = models.CharField(max_length=11, choices=JOB_TYPE, default='FULL-TIME')
    department_name = models.ForeignKey(Departments, on_delete=models.PROTECT)
    salary = models.CharField(max_length=20)
    slug = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.job_title


class Job_Apply(models.Model):
    full_name = models.CharField(max_length=50)
    email_address = models.CharField(max_length=50)
    phone_number = models.IntegerField()
    file = models.FileField(upload_to='file')
    job_title = models.ForeignKey(Circular, on_delete=models.PROTECT)

    def __str__(self):
        return self.full_name

others/forms.py
from django import forms
from .models import Job_Apply


class Job_Form(forms.ModelForm):
    class Meta:
        model = Job_Apply
        fields = ['full_name', 'email_address', 'phone_number', 'file']

others/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Job_Apply
from .models import Team, Circular, Departments, Contact
from django.contrib import messages


def contact(request):
    if request.method == 'POST':
        full_name = request.POST['full_name']
        emailaddress = request.POST['emailaddress']
        subject = request.POST['sendersubject']
        message = request.POST['sendermessage']

        x = Contact.objects.create(full_name=full_name, emailaddress=emailaddress, subject=subject, message=message)
        x.save()
        return redirect('/')
    else:
        return render(request, 'others/contact.html')


def about(request):
    team = Team.objects.all()
    return render(request, 'others/about.html', {'team': team})


def career(request, dept_slug=None):
    dept = None
    circular = Circular.objects.all()
    department = Departments.objects.all()
    if dept_slug:
        dept = get_object_or_404(Departments, slug=dept_slug)
        circular = circular.filter(department_name=dept)
    return render(request, 'others/career.html', {'circular': circular, 'department': department, 'dept': dept})


def job_details(request):
    job = get_object_or_404(Circular, slug=request.GET.get('id'))
    return render(request, 'others/job_details.html', {'job': job})


def job_apply(request):
    job = get_object_or_404(Circular, slug=request.GET.get('id'))
    if request.method == 'POST':
        full_name = request.POST['full_name']
        emailaddress = request.POST['emailaddress']
        phone_number = request.POST['phone_number']
        file = request.POST['file']
        x = Job_Apply.objects.create(full_name=full_name, email_address=emailaddress, phone_number=phone_number,
                                     file=file, job_title=job)
        x.save()
        messages.success(request, 'Application is submitted successfully')
        return redirect('others:career')

    else:
        return render(request, 'others/job_apply_form.html', {'job': job})

others/templates/others/about.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}

    <!-- Body Start -->
    <div class="wrapper">

		<div class="life-gambo">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="default-title left-text">
							<h2>About Danish Food Limited</h2>
							<p>Customers Deserve Better</p>
							<img src="{% static 'images/line.svg' %}" alt="">
						</div>
						<div class="about-content">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ac sodales sapien. Sed pellentesque, quam in ornare tincidunt, magna augue placerat nunc, ut facilisis nibh ipsum non ipsum. Cras ac eros non neque viverra consequat sed at est. Fusce efficitur, lacus nec dignissim tincidunt, diam sapien rhoncus neque, at tristique sapien nibh sed neque. Proin in neque in purus luctus facilisis. Donec viverra ligula quis lorem viverra consequat. Aliquam condimentum id enim volutpat rutrum. Donec semper iaculis convallis. Praesent quis elit eget ligula facilisis mattis. Praesent sed euismod dui. Suspendisse imperdiet vel quam nec venenatis. Suspendisse dictum blandit quam, vitae auctor enim gravida et. Sed id dictum nibh. Proin egestas massa sit amet tincidunt aliquet.</p>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="about-img">
							<img src="{% static 'images/about.svg' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="about-steps-group white-bg">
			<div class="container">
				<div class="row">
					<div class="col-lg-3">
						<div class="about-step">
							<div class="about-step-img">
								<img src="{% static 'images/about/icon-1.svg' %}" alt="">
							</div>
							<h4>100+</h4>
							<p>Products</p>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="about-step">
							<div class="about-step-img">
								<img src="{% static 'images/about/icon-2.svg' %}" alt="">
							</div>
							<h4>30+</h4>
							<p>Countries</p>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="about-step">
							<div class="about-step-img">
								<img src="{% static 'images/about/icon-3.svg' %}" alt="">
							</div>
							<h4>5000+</h4>
							<p>Employees</p>
						</div>
					</div>
					<div class="col-lg-3">
						<div class="about-step">
							<div class="about-step-img">
								<img src="{% static 'images/about/icon-4.svg' %}" alt="">
							</div>
							<h4>23+</h4>
							<p>Partner</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="life-gambo">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">

						<div class="default-title">
							<h2>Our Team</h2>
							<p>Teamwork Makes the Dream Work</p>
							<img src="" alt="">
						</div>
						<div class="dd-content">

							<div class="owl-carousel team-slider owl-theme">
                                {% for member in team %}
								<div class="item">
									<div class="team-item">
										<div class="team-img">
											<img src="/media/{{ member.image }}" alt="">
										</div>
										<h4>{{ member.name }}</h4>
										<span>{{ member.position }}</span>
										<ul class="team-social">
											<li>{% if member.facebookId %}<a  href="{{ member.facebookId }}" class="scl-btn hover-btn"><i class="fab fa-facebook-f"></i></a>{% else %}<div class="scl-btn hover-btn"><i class="fab fa-facebook-f"></i></div></li>{% endif %}
                                            <li>{% if member.linkedinId %}<a  href="{{ member.linkedinId }}"  class="scl-btn hover-btn"><i class="fab fa-linkedin-in"></i></a>{% else %}<div class="scl-btn hover-btn"><i class="fab fa-linkedin-in"></i></div></li>{% endif %}
										</ul>
									</div>
								</div>
                                {% endfor %}

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="how-order-gambo">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="default-title">
							<h2>What do we want to do?</h2>
							<img src="images/line.svg" alt="">
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="how-order-steps">
							<div class="how-order-icon">
								<i class="uil uil-search"></i>
							</div>
							<h4>Our responsible feature title here</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="how-order-steps">
							<div class="how-order-icon">
								<i class="uil uil-shopping-basket"></i>
							</div>
							<h4>Our responsible feature title here</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="how-order-steps">
							<div class="how-order-icon">
								<i class="uil uil-stopwatch"></i>
							</div>
							<h4>Our responsible feature title here</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="how-order-steps">
							<div class="how-order-icon">
								<i class="uil uil-money-bill"></i>
							</div>
							<h4>Our responsible feature title here</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="how-order-steps">
							<div class="how-order-icon">
								<i class="uil uil-truck"></i>
							</div>
							<h4>Our responsible feature title here</h4>
						</div>
					</div>
					<div class="col-lg-4 col-md-6">
						<div class="how-order-steps">
							<div class="how-order-icon">
								<i class="uil uil-smile"></i>
							</div>
							<h4>Our responsible feature title here</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	<!-- Body End -->

{% endblock %}

others/templates/others/career.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
    <!-- Body Start -->
	<div class="wrapper">
		<div class="life-gambo white-bg">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="default-title">
                             <div class="form-group">
                                {% if messages %}
                                    <ul class="messages">
                                    {% for message in messages %}
                                        <li>
                                        <div class="alert alert-success">{{ message }}
                                             <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                     <span aria-hidden="true">&times;</span>
                                             </button>
                                        </div>
                                        </li>
                                    {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
							<h2>The benefits of working at Danish Food Limited</h2>
							<p>We want you to feel like home when you're working at Gambo and for that we've curated a great set of benefits for you.</p>
							<img src="{% static 'images/line.svg' %}" alt="">
						</div>
					</div>
				</div>
			</div>
        </div>

		<div class="jobs-gambo my-5">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="default-title">
							<h2>Work With Us</h2>
							<p>Have the appetite to discover, learn and build with the team.</p>
							<img src="{% static 'images/line.svg' %}" alt="">
						</div>
					</div>
					<div class="col-md-4">
						<div class="pdpt-bg">
							<div class="pd-20">
								<div class="all-departments">
									<h4>Departments</h4>
                                    <ul>
                                        <li>
                                            <a href="{% url "others:career" %}">All</a>
                                        </li>
                                    {% for dp in department %}
                                        <li>
                                        <a href="{{ dp.get_absolute_url }}">{{ dp.department_name }}</a>
                                        </li>
                                    {% endfor %}
                                    </ul>
                                </div>
							</div>
						</div>
					</div>
					<div class="col-md-8">
                    {% for job in circular %}
						<a href="{% url 'others:job_details' %}?id={{ job.slug }}" class="job-bg1">
							<div class="job-item">
                                <h4> {{ job.job_title }}</h4>
                                <h5 > <pre class="tab" , style="color: #0d71bb"> {{ job.job_type }}      {{ job.salary }}  </pre></h5>
							</div>
							<i class="uil uil-angle-right-b arrow-icon"></i>
						</a>

                        {% endfor %}
                    </div>
				</div>
			</div>
		</div>
    </div>
	<!-- Body End -->

{% endblock %}

others/templates/others/contact.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
   	<!-- Body Start -->
    <div class="wrapper">
		<div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
								<li class="breadcrumb-item active" aria-current="page">Contact Us</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<div class="all-product-grid">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<h2>Fancy Group BD</h2>
						<h5>Ali Bhaban(5th Floor),92,Kazi Nazrul Islam Avenue, Kawran Bazar, Dhaka-1215</h5>
						<h5>Email: info@fancygroupbd.com</h5>
						<h5>Cellphone: 0258150228</h5>
					</div>
					<div class="col-lg-6 col-md-6">
						<div class="contact-title">
							<h2>Submit customer service request</h2>
							<p>If you have a question about our service or have an issue to report, please send a request and we will get back to you as soon as possible.</p>
						</div>
						<div class="contact-form">
							<form action="{% url 'others:contact' %}" method="post">{% csrf_token %}
								<div class="form-group mt-1">
									<label class="control-label">Full Name*</label>
									<div class="ui search focus">
										<div class="ui left icon input swdh11 swdh19">
											<input class="prompt srch_explore" type="text" name="full_name" id="full_name" required="" placeholder="Your Full Name">
										</div>
									</div>
								</div>
								<div class="form-group mt-1">
									<label class="control-label">Email Address*</label>
									<div class="ui search focus">
										<div class="ui left icon input swdh11 swdh19">
											<input class="prompt srch_explore" type="email" name="emailaddress" id="emailaddress" required="" placeholder="Your Email Address">
										</div>
									</div>
								</div>
								<div class="form-group mt-1">
									<label class="control-label">Subject*</label>
									<div class="ui search focus">
										<div class="ui left icon input swdh11 swdh19">
											<input class="prompt srch_explore" type="text" name="sendersubject" id="sendersubject" required="" placeholder="Subject">
										</div>
									</div>
								</div>
								<div class="form-group mt-1">
									<div class="field">
										<label class="control-label">Message*</label>
										<textarea rows="2" class="form-control" id="sendermessage" name="sendermessage" required="" placeholder="Write Message"></textarea>
									</div>
								</div>
								<button class="next-btn16 hover-btn mt-3" type="submit" data-btntext-sending="Sending...">Submit Request</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	<!-- Body End -->
    
{% endblock %}

others/templates/others/job_apply_form.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
   	<!-- Body Start -->
    <div class="wrapper">
		<div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<div class="all-product-grid">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6">
						<div class="contact-title">
							<h2>Apply Here for the position of {{ job.job_title }}</h2>
						</div>
						<div class="contact-form">
							 <form action="{% url 'others:job_apply' %}?id={{ job.slug }}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group mt-1">
                                        <label class="control-label">Full Name*</label>
                                        <div class="ui search focus">
                                            <div class="ui left icon input swdh11 swdh19">
                                                <input class="prompt srch_explore" type="text" name="full_name" id="full_name" required="" placeholder="Your Full Name">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-1">
                                        <label class="control-label">Email Address*</label>
                                        <div class="ui search focus">
                                            <div class="ui left icon input swdh11 swdh19">
                                                <input class="prompt srch_explore" type="email" name="emailaddress" id="emailaddress" required="" placeholder="Your Email Address">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-1">
                                        <label class="control-label">Phone Number*</label>
                                        <div class="ui search focus">
                                            <div class="ui left icon input swdh11 swdh19">
                                                <input class="prompt srch_explore" type="number" name="phone_number" id="phone" required="" placeholder="Your Phone Number">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group mt-1">
                                        <label class="control-label">Upload your CV/Resume*</label>
                                        <div  class="ui search focus">
                                            <input style="padding: 8px" class="prompt srch_explore" type="file" name="file" id="file" required="" placeholder="file">
                                        </div>
                                    </div>
                                    <button  class="next-btn16 hover-btn mt-3" type="submit" data-btntext-sending="Sending...">Submit Application</button>
                             </form>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	<!-- Body End -->
{% endblock %}

others/templates/others/job_details.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
   	<!-- Body Start -->
    <div class="wrapper">
		<div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">{{ job.job_title }}</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<div class="all-product-grid">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-6">
						<div class="contact-form">
                            <h1>{{ job.job_title }}</h1>
                            <p style="color: black"> {{ job.job_details|safe }}<br>
                                <b>{{ job.job_type }}<br>
                                {{ job.department_name }}<br>
                                    {{ job.salary }}</b>
                            </p>
                            <div class="col-md-12">
                                <div class="more-product-btn">
                                    <button class="show-more-btn hover-btn" onclick="window.location.href = '{% url 'others:job_apply' %}?id={{ job.slug }}';">Apply</button>
                                </div>
                            </div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	<!-- Body End -->
{% endblock %}