FancyProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('product/', include('product.urls')),
    path('others/', include('others.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import Bloghome, Blogdetails, AddPost,UpdatePost,DeletePost

app_name = 'blog'

urlpatterns = [
    path('', Bloghome.as_view(), name='bloghome'),
    path('blogdetails/<int:pk>', Blogdetails.as_view(), name='blogdetails'),
    # path('blogdetails/<slug:slug>', Blogdetails.as_view(), name='blogdetails'),
    # path('add_post/', AddPost.as_view(), name='add_post'),
    # path('edit_post/<slug:slug>', UpdatePost.as_view(), name='edit_post'),
    # path('delete_post/<slug:slug>/remove', DeletePost.as_view(), name='delete_post'),
    # # path('like/<int:pk>', LikeView, name='like_post'),
]

user/urls.py
from django.urls import path
from .views import UserRegister

app_name = 'user'

urlpatterns = [
    path('register/', UserRegister.as_view(), name='register'),

]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.TextField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null= True)
    blog_image = models.ImageField(upload_to='blognew/image', default='')
    time = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    slug = models.SlugField(null=True)

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + '  |  ' + str(self.author)

    def snippet(self):
        return self.body[:30]

    def get_absolute_url(self):
        return reverse('blog:blogdetails', kwargs={'slug': self.slug})

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','body','blog_image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value':'', 'id':'elder', 'type':'hidden'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'blog_image': forms.FileInput(attrs={'class': 'form-control'}),
        }



class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body','blog_image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'blog_image': forms.FileInput(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView , CreateView, UpdateView, DeleteView
from .models import Post
from .forms import PostForm,EditForm

# def LikeView(request,pk):
#     post =get_object_or_404(Post, id=request.POST.get('post_id'))
#     liked = False
#     if post.likes.filter(id=request.user.id).exists():
#         post.likes.remove(request.user)
#         liked = False
#     else:
#         post.likes.add(request.user)
#         liked = True
#     return HttpResponseRedirect(reverse('blog:blogdetails', args=[str(pk)]))


class Bloghome(ListView):
    model = Post
    template_name = 'blog/blog.html'
    ordering = ['id']
    paginate_by = 2


class Blogdetails(DetailView):
    model = Post
    template_name = 'blog/blogdetails.html'

    # def get_context_data(self, **kwargs):
    #     context = super(Blogdetails, self).get_context_data(**kwargs)
    #     stuff = get_object_or_404(Post, id=self.kwargs['pk'])
    #     total_likes = stuff.total_likes()
    #
    #     liked = False
    #     if stuff.likes.filter(id=self.request.user.id).exists():
    #         liked = True
    #     context ["total_likes"] = total_likes
    #     context["liked"] = liked
    #     return context


class AddPost(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/add_post.html'


class UpdatePost(UpdateView):
    model = Post
    form_class = EditForm
    template_name = "blog/update_post.html"


class DeletePost(DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = reverse_lazy('blog:bloghome')

blog/templates/blog/add_post.html
{% extends 'home/base.html' %}
{% block body %}

   	<!-- Body Start -->
    <div class="wrapper">
            <div class="gambo-Breadcrumb">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                                    <li class="breadcrumb-item"><a href="{% url 'blog:bloghome' %}">Our Blog</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
          {% if user.is_authenticated %}
                        <div class="gambo-Breadcrumb">
                            <div class="container">
                               <h1>Add Blog</h1>
                                <div class="form-group">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.media }}
                                        {{ form.as_p }}
                                        <button class="btn btn-secondary">post</button>
                                    </form>
                                </div>
                            </div>
                        </div>
              <script>
                 var name = "{{ user.id }}";
                  document.getElementById("elder").value = name;
              </script>

          {% else %}
               <h3 style="text-align: center;color:red">You are not allowed here! </h3>
          {% endif %}
    </div>
	<!-- Body End -->



{% endblock %}

blog/templates/blog/blog.html
{% extends 'home/base.html' %}
{% block body %}
   	<!-- Body Start -->
	<div class="wrapper wrapper-blog">
		<div class="blog-gambo" style="margin-top:20px">
			<div class="container">
{#            {% if user.is_authenticated %}#}
{#                <a type="button" class="btn btn-secondary" href="{% url 'blog:add_post' %}">Add_Post</a>#}
{#                <a type="button" class="btn btn-secondary" href="{% url 'logout' %}">Logout</a>#}
{##}
{#            {% else %}#}
{#                <a type="button" class="btn btn-secondary" href="{% url 'user:register' %}">Register</a>#}
{#                <a type="button" class="btn btn-secondary" href="{% url 'login' %}">Login</a>#}
{##}
{#            {% endif %}#}
            	<div class="row">
                    {% for post in page_obj %}
                        <div class="col-lg-6 col-md-6">
                            <div class="blog-item">
                                <a href="{% url 'blog:blogdetails' post.pk %}" class="blog-img">
                                    <img src="/media/{{ post.blog_image }}" alt="noimg">
                                </a>
{#                                <div class="date-icons-group">#}
{#                                    <div class="blog-time sz-14">{{ post.time }}</div>#}
{#                                    <ul class="like-share-icons">#}
{#                                        <li>#}
{#                                            <a href="#" class="like-share"><i class="uil uil-thumbs-up"></i><span>5</span></a>#}
{#                                        </li>#}
{#                                        <li>#}
{#                                            <a href="#" class="like-share"><i class="uil uil-share-alt"></i></a>#}
{#                                        </li>#}
{#                                    </ul>#}
{#                                </div>#}
                                <div class="blog-detail">
                                    <h4>{{ post.title }}</h4>
{#                                    <small>By:{{ post.author }}</small>#}
                                    <p>{{ post.snippet|safe }}</p>
                                    <a href="{% url 'blog:blogdetails' post.pk %}">Read More</a>
                                </div>
                            </div>
                        </div>
					{% endfor %}
                </div>
                <div>
                    <span>
                        {% if page_obj.has_next %}
                            <div class="col-md-12">
                                <div class="more-product-btn">
                                    <button class="show-more-btn hover-btn" onclick="window.location.href = '?page={{ page_obj.next_page_number }}';">Show More</button>
                                </div>
                            </div>
                       {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
	<!-- Body End -->

{% endblock %}

blog/templates/blog/blogdetails.html
{% extends 'home/base.html' %}
{% load static %}
{% load social_share %}
{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <style>
    .share-btn-container {
        background: transparent;
        display: flex;
        flex-direction: row;
        padding: 3px;
    }

    .share-btn-container a i {
        font-size: 17px;
    }

    .share-btn-container a {
        margin: 0 10px;
        transition: 500ms;
    }

     .share-btn-container a:hover {
         transform: scale(1.5);
     }

    .share-btn-container .fa-facebook{
        {#color: #3b5998;#}
        color: black;
    }

    .share-btn-container .fa-twitter{
        {#color: #1da1f2;#}
        color: black;
    }

    .share-btn-container .fa-pinterest {
        color: black;
        {#color: #bd081c;#}
    }

    .share-btn-container .fa-whatsapp{
        color: black;
        {#color: #25d366;#}
    }

    .share-btn-container .fa-linkedin{
        color: black;
        {#color: #0077b5;#}
    }

    </style>

{% endblock header %}
{% block body %}
	<!-- Body Start -->
	<div class="wrapper">
		<div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
								<li class="breadcrumb-item"><a href="{% url 'blog:bloghome' %}">Blog</a></li>
								<li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
{#                                {% if user.is_authenticated %}#}
{#                                    {% if user.id == post.author.id %}#}
{#                                        <li class="breadcrumb-item"><a href="{% url 'blog:edit_post' post.slug %}">Edit</a></li>#}
{#                                        <li class="breadcrumb-item" ><a href="{% url 'blog:delete_post' post.slug%}" style="color: red">(Delete)</a></li>#}
{#                                    {% endif %}#}
{#                                {% endif %}#}
                            </ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<div class="blog-dt-vw parallax" style=" background-image: url('/media/{{ post.blog_image }}');">
			<div class="blog-inner">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							<h1>{{ post.title }}</h1>
							<div class="extra-info">
{#								<span class="entry-date">{{ post.time }}</span>#}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="blog-single-dts-text">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-10">
						<div class="bb-des12">
							 <div class="blog-des-dt142">
                                 {{ post.body|safe }}
                             </div>
                             <br/>
                             <div class="share-btn-container">
                                 <a target="_blank" href="#" class="facebook-bt">
                                     <i class="fab fa-facebook"></i>
                                 </a>
                                 <a target="_blank" href="#" class="twitter-bt">
                                     <i class="fab fa-twitter"></i>
                                 </a>
                                 <a target="_blank" href="#" class="pinterest-bt">
                                     <i class="fab fa-pinterest"></i>
                                 </a>
                                 <a target="_blank" href="#" class="whatsapp-bt">
                                     <i class="fab fa-whatsapp"></i>
                                 </a>
                                 <a target="_blank" href="#" class="linkedin-bt">
                                     <i class="fab fa-linkedin"></i>
                                 </a>
                             </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Body End -->
    <script src="{% static 'js/blog.js' %}"></script>
{% endblock %}

blog/templates/blog/blognew.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
{% for post in object_list %}
    <li><a href="{% url 'blog:blogdetails' post.pk %}">{{ post.title }} - {{ post.author }}</a><br/>
</li>

{% endfor %}
</ul>
</body>
</html>

blog/templates/blog/delete_post.html
{% extends 'home/base.html' %}
{% block body %}

   	<!-- Body Start -->
    <div class="wrapper ">

        <div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
								<li class="breadcrumb-item"><a href="{% url 'blog:bloghome' %}">Our Blog</a></li>
                                <li class="breadcrumb-item "><a href="{% url 'blog:blogdetails' post.slug %}">Blog Detail View</a></li>
                                <li class="breadcrumb-item"><a href="{% url 'blog:edit_post' post.slug %}">Edit</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="color: red">(Delete)</li>

                            </ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
              {% if user.is_authenticated %}
                  {% if user.id == post.author.id %}
                        <div class="gambo-Breadcrumb">
                            <div class="container ">
                               <h1>Delete Post {{ post.title }}</h1>
                                <div class="form-group">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <strong>Are you sure?!</strong><br/>
                                        <button class="btn btn-primary">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                  {% else %}
                       <h3 style="text-align: center;color:red">You are not allowed here! </h3>
                  {% endif %}
              {% else %}
                   <h3 style="text-align: center;color:red">You are not allowed here! </h3>
              {% endif %}
    </div>
	<!-- Body End -->

{% endblock %}

blog/templates/blog/update_post.html
{% extends 'home/base.html' %}
{% block body %}

   	<!-- Body Start -->
    <div class="wrapper">
         <div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
								<li class="breadcrumb-item"><a href="{% url 'blog:bloghome' %}">Our Blog</a></li>
                                <li class="breadcrumb-item "><a href="{% url 'blog:blogdetails' post.slug %}">Blog Detail View</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Edit</li>
                                <li class="breadcrumb-item active" style="color: red"><a href="{% url 'blog:delete_post' post.slug %}">(Delete)</a></li>

                            </ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
              {% if user.is_authenticated %}
                   {% if user.id == post.author.id %}
                        <div class="gambo-Breadcrumb">
                            <div class="container">
                               <h1>Update your Post Here</h1>
                                <div class="form-group">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.media }}
                                        {{ form.as_p }}
                                        <button class="btn btn-secondary">Update_post</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                   {% else %}
                        <h3 style="text-align: center;color:red">You are not allowed here! </h3>
                   {% endif %}
              {% else %}
                   <h3 style="text-align: center;color:red">You are not allowed here! </h3>
              {% endif %}
    </div>
	<!-- Body End -->



{% endblock %}