FancyProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('product/', include('product.urls')),
    path('others/', include('others.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import Bloghome, Blogdetails, AddPost,UpdatePost,DeletePost

app_name = 'blog'

urlpatterns = [
    path('', Bloghome.as_view(), name='bloghome'),
    path('blogdetails/<int:pk>', Blogdetails.as_view(), name='blogdetails'),
    # path('blogdetails/<slug:slug>', Blogdetails.as_view(), name='blogdetails'),
    # path('add_post/', AddPost.as_view(), name='add_post'),
    # path('edit_post/<slug:slug>', UpdatePost.as_view(), name='edit_post'),
    # path('delete_post/<slug:slug>/remove', DeletePost.as_view(), name='delete_post'),
    # # path('like/<int:pk>', LikeView, name='like_post'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.product, name='product'),
    path('<slug>', views.product, name='cat_slug'),
    path('product_details/<slug>', views.product_details, name='product_details'),
]

product/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_resized import ResizedImageField
# Create your models here.


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category/image')
    slug = models.SlugField()

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('product:cat_slug', args=[self.slug, ])


class Products(models.Model):
    PRODUCT_STATUS = (
        ('AVAILABLE', 'AVAILABLE'),
        ('UNAVAILABLE', 'UNAVAILABLE'),
        ('COMING_SOON', 'COMING_SOON'),
    )
    product_name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    product_status = models.CharField(max_length=20, choices=PRODUCT_STATUS, default='AVAILABLE')
    product_summery = models.TextField(default='product')
    Product_details = RichTextField(blank=True, null= True)
    price = models.IntegerField(default=0)
    image = ResizedImageField(size=[300, 300], crop=['middle', 'center'], quality=100,upload_to='product/image', default='')
    post_date = models.DateTimeField(default=timezone.now)
    slug = models.CharField(max_length=255, unique=True, default='abc')


    def __str__(self):
        return self.product_name

product/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Products, Category

# Create your views here.

def product(request,slug=None):
    cat = None
    product = Products.objects.all()
    category = Category.objects.all()
    paginator = Paginator(product, 4)
    page = request.GET.get('page')
    try:
        product = paginator.page(page)
    except PageNotAnInteger:
        product = paginator.page(1)
    except EmptyPage:
        product = paginator.page(paginator.num_pages)

    if slug:
        product = Products.objects.all()
        cat = get_object_or_404(category, slug=slug)
        product = product.filter(category=cat)
        paginator = Paginator(product, 1)
        page = request.GET.get('page')
        try:
            product = paginator.page(page)
        except PageNotAnInteger:
            product = paginator.page(1)
        except EmptyPage:
            product = paginator.page(paginator.num_pages)
    return render(request, 'product/product.html', {'product': product, 'category': category,'cat':cat, 'page': page})


def product_details(request, slug):
    product = get_object_or_404(Products, slug=slug)
    allproduct = Products.objects.filter(category=product.category)
    return render(request, 'product/product_details.html', {'product': product, 'allproduct':allproduct})

product/templates/product/product.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
	<!-- Body Start -->
    <div class="wrapper">
		<div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
								<li class="breadcrumb-item active" aria-current="page">All Products</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<div class="all-product-grid">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="product-top-dt">
							<div class="product-left-title">
								<h2>All Products</h2>
							</div>
{#							<a class="filter-btn pull-bs-canvas-right">Filters</a>#}
							<div class="product-sort">
								<div class="ui selection dropdown vchrt-dropdown">
									<input name="gender" type="hidden" value="default">
									<i class="dropdown icon d-icon"></i>
									<div class="text">{% if cat.category_name %}{{ cat.category_name }}{% else %}Category{% endif %}</div>
									<div class="menu">
                                        <a class="item" href="{% url "product:product" %}">All</a>
                                        {% for c in category %}
                                            <a class="item"  href="{{ c.get_absolute_url }}">{{ c.category_name }}</a>
                                        {% endfor %}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="product-list-view">
					<div class="row">
                        {% for item in product %}
                            <div class="col-lg-3 col-md-6">
                                <div class="product-item mb-30">
                                    <a href="{% url 'product:product_details' slug=item.slug %}" class="product-img">
                                        <img src="/media/{{item.image}}" alt="">
                                    </a>
                                    <div class="product-text-dt">
                                        <p>{{item.product_status}}</p>
                                        <h4>{{ item.product_name }}</h4>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
					</div>
                    <div>
                        <span>
                            {% if product.has_next %}
                                <div class="col-md-12">
                                    <div class="more-product-btn">
                                        <button class="show-more-btn hover-btn" onclick="window.location.href = '?page={{ product.next_page_number }}';">Show More</button>
                                    </div>
                                </div>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/product_details.html
{% extends 'home/base.html' %}
{% load static %}
{% load social_share %}
{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <style>
    p {
      color: black;
    }
    .share-btn-container {
        background: transparent;
        display: flex;
        flex-direction: row;
        padding: 16px;
    }

    .share-btn-container a i {
        font-size: 18px;
    }

    .share-btn-container a {
        margin: 0 10px;
        transition: 500ms;
    }

     .share-btn-container a:hover {
         transform: scale(1.2);
     }

    .share-btn-container .fa-facebook{
        {#color: #3b5998;#}
        color: black;
    }

    .share-btn-container .fa-twitter{
        {#color: #1da1f2;#}
        color: black;
    }

    .share-btn-container .fa-pinterest{
        {#color: #bd081c;#}
        color: black;
    }

    .share-btn-container .fa-whatsapp{
        {#color: #25d366;#}
        color: black;
    }

    .share-btn-container .fa-linkedin{
        {#color: #0077b5;#}
        color: black;
    }

    </style>
{% endblock header %}

{% block body %}
   	<!-- Body Start -->
	<div class="wrapper">
		<div class="gambo-Breadcrumb">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="/">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category}}</a></li>
								<li class="breadcrumb-item active" aria-current="page">{{ product.product_name }}</li>
							</ol>
						</nav>
					</div>
				</div>
			</div>
		</div>
		<div class="all-product-grid">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="product-dt-view">
							<div class="row">
								<div class="col-lg-4 col-md-4">
										<div class="item">
											<img class="pinterest_img" src="/media/{{product.image}}" alt="noimage">
										</div>
									<div id="sync2" class="owl-carousel owl-theme">

									</div>
								</div>
								<div class="col-lg-8 col-md-8">
									<div class="product-dt-right">
										<h2>{{ product.product_name }}</h2>
										<div class="no-stock">
											<p class="stock-qty"><span>{{ product.product_status }}</span></p>
										</div>
										<p class="pp-descp">{{product.product_summery }}</p>
                                        <div class="share-btn-container">
                                             <a target="_blank" href="#" class="facebook_btn">
                                                <i class="fab fa-facebook"></i>
                                             </a>
                                             <a target="_blank" href="#" class="twitter_btn">
                                                <i class="fab fa-twitter"></i>
                                             </a>
                                             <a target="_blank" href="#" class="pinterest_btn">
                                                <i class="fab fa-pinterest"></i>
                                             </a>
                                             <a target="_blank" href="#" class="whatsapp_btn">
                                                <i class="fab fa-whatsapp"></i>
                                             </a>
                                             <a target="_blank" href="#" class="linkedin_btn">
                                                <i class="fab fa-linkedin"></i>
                                             </a>
                                        </div>
									</div>
								</div>
							</div>
						</div>
                        <br>
                        <div class="product-dt-view">
							<div class="row">
								<div class="col-lg-12 col-md-12">
							       {{product.Product_details|safe }}
							    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Featured Products Start -->
            <div class="section145">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="main-title-tt">
                                <div class="main-title-left">
                                    <span>For You</span>
                                    <h2>Similar Products</h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                             <div class="owl-carousel featured-slider owl-theme">
                                 {% for item in allproduct %}
                                      <div class="item">
                                          <div class="product-item">
                                                <a href="{% url 'product:product_details' slug=item.slug%}" class="product-img">
                                                    <img src="/media/{{item.image}}" alt="">
                                                </a>
                                                <div class="product-text-dt">
                                                    <p>{{item.product_status}}</p>
                                                    <h4>{{ item.product_name }}</h4>
                                                </div>
                                            </div>
                                        </div>
                                 {% endfor %}
                             </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Featured Products End -->
        </div>
    </div>
	<!-- Body End -->
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}